import esbuild from "esbuild";
import process from "process";
import { builtinModules, createRequire } from "module";
import fs from "fs/promises";
import path from "path";
import { foliatePlugins } from "./scripts/foliate-build.mjs";

const require = createRequire(import.meta.url);
const prod = process.argv[2] === "production";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, visit the plugin's repository

This bundle includes pdf.js (https://github.com/mozilla/pdf.js),
Copyright Mozilla Foundation and contributors, licensed under the
Apache License 2.0, and foliate-js (https://github.com/johnfactotum/foliate-js),
Copyright John Factotum, licensed under the MIT License, which itself bundles
zip.js and fflate. See THIRD_PARTY_NOTICES.md.
*/
`;

/**
 * Turns `pdfjs-worker-source` into a JS string holding the whole pdf.js worker,
 * and `pdfjs-cmaps` into a { [cMapName]: base64 } table.
 *
 * Both are inlined so the plugin stays a single main.js, which is the only
 * artifact Obsidian's community-plugin installer ships.
 */
const inlineAssets = {
  name: "pdfjs-inline-assets",
  setup(build) {
    build.onResolve({ filter: /^pdfjs-(worker-source|cmaps)$/ }, (args) => ({
      path: args.path,
      namespace: "pdfjs-asset",
    }));

    build.onLoad({ filter: /.*/, namespace: "pdfjs-asset" }, async (args) => {
      if (args.path === "pdfjs-worker-source") {
        const file = require.resolve(
          `pdfjs-dist/legacy/build/pdf.worker${prod ? ".min" : ""}.mjs`
        );
        return { contents: await fs.readFile(file, "utf8"), loader: "text" };
      }

      const cmapDir = path.join(
        path.dirname(require.resolve("pdfjs-dist/package.json")),
        "cmaps"
      );
      const names = (await fs.readdir(cmapDir)).filter((n) => n.endsWith(".bcmap")).sort();
      const table = {};
      for (const name of names) {
        const buf = await fs.readFile(path.join(cmapDir, name));
        table[name.replace(/\.bcmap$/, "")] = buf.toString("base64");
      }
      return { contents: JSON.stringify(table), loader: "json" };
    });
  },
};

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  plugins: [inlineAssets, ...foliatePlugins],
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  target: "es2022",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
  define: { "process.env.NODE_ENV": prod ? '"production"' : '"development"' },
});

if (prod) {
  await context.rebuild();
  // A bare `customElements.define()` means a vendored module defines an element
  // the build-time guard did not rewrite, and BookView would then load exactly
  // once per Obsidian window: the second enable throws before onload() runs and
  // takes the whole plugin down. Cheap to check, expensive to ship.
  const bundle = await fs.readFile("main.js", "utf8");
  if (bundle.includes("customElements.define(")) {
    console.error(
      "Build failed: an unguarded customElements.define() reached main.js. " +
        "See guardFoliateCustomElements in scripts/foliate-build.mjs."
    );
    process.exit(1);
  }
  process.exit(0);
} else {
  await context.watch();
}
